website redesign
RazorSh4rk/random-word-api pull request #26
Opened 2022-10-16 21:31 UTC by PixelatedLagg

2022-10-19 21:00 UTC, RazorSh4rk commented on templates/index.html
> +            <h3 onclick="window.location.replace('https://github.com/RazorSh4rk/random-word-api');">Github</h3>
Could you just make this a link pls, you cant use the back button like this

2022-10-19 21:02 UTC, RazorSh4rk requested changes
The site looks great, way better than what i could do :) Could you please do those 2 small things i mentioned?

2022-10-19 21:02 UTC, RazorSh4rk commented on templates/index.html
> +            <h3 onclick="endpoints();">Endpoints</h3>
If you could have some pointer that im looking at >this< page right now that would make this perfect

2022-10-20 03:36 UTC, PixelatedLagg commented
working on replacing headers with links and smooth page indication

2023-05-11 22:59 UTC, closed without merging